# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Anul_4\PIU\HelloMail\designer\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1303, 789)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.emailContentWebEngine = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.emailContentWebEngine.setGeometry(QtCore.QRect(280, 130, 782, 651))
        self.emailContentWebEngine.setStyleSheet("QWebEngineView{\n"
"                        border: 1px solid ;\n"
"                        border-color:rgb(0, 0, 0)\n"
"                        }")
        self.emailContentWebEngine.setObjectName("emailContentWebEngine")
        self.testPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.testPushButton.setGeometry(QtCore.QRect(40, 30, 93, 28))
        self.testPushButton.setObjectName("testPushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.testPushButton.setText(_translate("MainWindow", "PushButton"))

