# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Catalin\Desktop\HelloMail\designer\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.emailContentWebEngine = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.emailContentWebEngine.setStyleSheet("QWebEngineView{\n"
"                                border: 1px solid ;\n"
"                                border-color:rgb(0, 0, 0)\n"
"                                }")
        self.emailContentWebEngine.setObjectName("emailContentWebEngine")
        self.verticalLayout.addWidget(self.emailContentWebEngine)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

