# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Anul_4\PIU\HelloMail\designer\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.emailContentWebEngine = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.emailContentWebEngine.setGeometry(QtCore.QRect(9, 9, 782, 251))
        self.emailContentWebEngine.setStyleSheet("border: 1px solid ;\n"
"border-color:rgb(0, 0, 0)")
        self.emailContentWebEngine.setObjectName("emailContentWebEngine")
        self.emailContentTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.emailContentTextBrowser.setGeometry(QtCore.QRect(10, 270, 781, 321))
        self.emailContentTextBrowser.setObjectName("emailContentTextBrowser")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
from PyQt5 import QtWebEngineWidgets
